### PR TITLE
Feature/password reset email

### PR DESCRIPTION
**Pull request by Miikis**
# Description
This PR adds an endpoint `POST /reset-password`. Emails sent in the body of a request to this endpoint will trigger a password-reset email to be sent to that user's email — assuming that user exists. If that user doesn't exist, a 401 error is returned to the client. 

This PR also changes some environmental variables. I'll update the Heroku app (staging & production) with these environment variables right after this PR is submitted. Here's an exhaustive list of all the environment variables necessary to run the backend repo now.

```
DATABASE_URL="postgres://localhost/endrsd"
TEST_DATABASE_URL="postgres://localhost/test_endrsd"

# JWT SECRETS
AUTH_JWT_SECRET="something something"
EMAIL_JWT_SECRET="something else something else"

# Email Origin
EMAIL_ADDRESS_SENDER=<our-labs-15-email-address>
EMAIL_ADDRESS_PASSWORD=<our-labs-15-email-password>

# Setup Account Email
EMAIL_URL_RESET_PASSWORD="<base-url>/reset-password"
```

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Change Status

-   [X] Complete, tested, ready to review and merge
-   [ ] Complete, but not tested (may need new tests)
-   [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

-   [X] E2E Tests
-   [X] Manual email sending tests

# Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [ ] My code has been reviewed by at least one peer
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [X] My changes generate no new warnings
-   [X] I have added tests that prove my fix is effective or that my feature works
-   [X] New and existing unit tests pass locally with my changes
-   [X] There are no merge conflicts

### CODE REVIEW

**Comment by Miikis** [comment]
Actually going to wait till this PR is successfully merged before messing with the existing Heroku environment variables. Otherwise, our staging/production servers would be down until this PR is reviewed and merged.

**Comment by ticotheps** [comment]
Also, when I run 'yarn test' on this branch locally, 100% of the tests are passing!

Screen Shot 2019-09-17 at 2 37 16 PM

**Comment by ticotheps** [comment]
While running the "develop" branch on the front-end with your "feature/password-reset-email" branch on the back-end, I did receive this error in the console after logging out:
Screen Shot 2019-09-17 at 2 39 23 PM

**Comment by clem9281** [comment]
Set my NODE_ENV to production and I DID receive the email in my inbox, this is so cool 🔥 🔥 🔥

**Comment by ticotheps** [comment]
Like @clem9281, while running this branch locally, I was able to put "NODE_ENV=production" into my .env file and was able to receive an email from our labs15superteam@gmail.com account.

Screen Shot 2019-09-17 at 4 30 15 PM
Screen Shot 2019-09-17 at 4 30 31 PM

**Pull request merged**
